@startuml
class java.awt.Dimension
class java.awt.Toolkit
class java.awt.image.BufferedImage
class java.io.BufferedReader
class java.io.ByteArrayInputStream
class java.io.File
class java.io.FileOutputStream
class java.io.IOException
class java.io.InputStream
class java.io.InputStreamReader
class java.io.OutputStream
class java.io.PrintStream
class java.io.PrintWriter
class java.io.UnsupportedEncodingException
class java.lang.module.ModuleFinder
class java.lang.module.ModuleReference
class java.lang.reflect.Field
class java.lang.reflect.InvocationTargetException
class java.lang.reflect.Method
class java.net.InetAddress
class java.net.NetworkInterface
class java.net.Socket
class java.net.SocketException
class java.net.URL
class java.nio.file.DirectoryStream
class java.nio.file.Files
class java.nio.file.Path
class java.nio.file.Paths
class java.nio.file.StandardCopyOption
class java.sql.Array
class java.sql.DriverManager
class java.sql.PreparedStatement
class java.sql.ResultSet
class java.sql.SQLException
class java.sql.Timestamp
class java.time.LocalDate
class java.util.ArrayList
class java.util.Arrays
class java.util.Collections
class java.util.Optional
class java.util.ResourceBundle
class javafx.application.Application
class javafx.application.Platform
class javafx.collections.FXCollections
class javafx.collections.ObservableList
class javafx.event.ActionEvent
class javafx.event.EventHandler
class javafx.fxml.FXMLLoader
class javafx.geometry.Pos
class javafx.scene.Node
class javafx.scene.Parent
class javafx.scene.Scene
class javafx.scene.control.Alert
class javafx.scene.control.Alert.AlertType
class javafx.scene.control.Button
class javafx.scene.control.ChoiceBox
class javafx.scene.control.DatePicker
class javafx.scene.control.Label
class javafx.scene.control.PasswordField
class javafx.scene.control.TableCell
class javafx.scene.control.TableColumn
class javafx.scene.control.TableColumn.CellEditEvent
class javafx.scene.control.TableView
class javafx.scene.control.TextArea
class javafx.scene.control.TextField
class javafx.scene.control.TextInputDialog
class javafx.scene.control.cell.PropertyValueFactory
class javafx.scene.control.cell.TextFieldTableCell
class javafx.scene.layout.HBox
class javafx.scene.layout.VBox
class javafx.scene.paint.Color
class javafx.stage.Modality
class javafx.stage.Stage
class javafx.stage.StageStyle
class javafx.util.Callback
class javax.imageio.ImageIO
class javax.swing.ImageIcon
class javax.swing.JLabel
class javax.swing.JWindow
class javax.swing.SwingConstants
class network.pkgswitch.management.system.ApproveRejectUsersDocumentController
class network.pkgswitch.management.system.ConfigurationChangeHistoryDocumentController
class network.pkgswitch.management.system.Data
class network.pkgswitch.management.system.Database
class network.pkgswitch.management.system.EnterNewPasswordDocumentController
class network.pkgswitch.management.system.LoginDocumentController
class network.pkgswitch.management.system.LoginHistoryReportDocumentController
class network.pkgswitch.management.system.ManagerMainDocumentController
class network.pkgswitch.management.system.NetworkSwitchConfigurationCheckDocumentController
class network.pkgswitch.management.system.NetworkSwitchDiscoveryDocumentController
class network.pkgswitch.management.system.NetworkSwitchManagementDocumentController
class network.pkgswitch.management.system.NetworkSwitchManagementSystem
class network.pkgswitch.management.system.PingTestDocumentController
class network.pkgswitch.management.system.RegisterNewUserDocumentController
class network.pkgswitch.management.system.SplashScreen
class network.pkgswitch.management.system.TechnicianMainDocumentController
class network.pkgswitch.management.system.UnbanUserDocumentController
class network.pkgswitch.management.system.UserManagementDocumentController
class network.pkgswitch.management.system.Utils
class network.pkgswitch.management.system.models.ConfigurationChangeHistory
class network.pkgswitch.management.system.models.LoginHistory
class network.pkgswitch.management.system.models.NetworkSwitch
class network.pkgswitch.management.system.models.NetworkSwitchConfiguration
class network.pkgswitch.management.system.models.UserManagement
class network.pkgswitch.management.system.services.NetworkSwitchConfigurationServices
class network.pkgswitch.management.system.services.NetworkSwitchServices
class network.pkgswitch.management.system.services.UserManagementServices
class org.apache.poi.ss.usermodel.HorizontalAlignment
class org.apache.poi.ss.usermodel.IndexedColors
class org.apache.poi.xssf.usermodel.XSSFCellStyle
class org.apache.poi.xssf.usermodel.XSSFFont
class org.apache.poi.xssf.usermodel.XSSFRow
class org.apache.poi.xssf.usermodel.XSSFSheet
class org.apache.poi.xssf.usermodel.XSSFWorkbook
class org.postgresql.jdbc.PgConnection
class org.postgresql.largeobject.LargeObject
class org.postgresql.largeobject.LargeObjectManager
@enduml